# If you face any issues, enable this for testing.
debug: false

timer:
  duration: 60 # Duration of the timer in seconds
  commands:
    - "say Hello, %player%!" # Command to be executed when timer ends (%player% is the plaeholder for the player)

# Is what it says it is. Provide minimum and maximum time.
random-timer:
  enabled: false
  min: 1000
  max: 1000

features:
  # Message to be sent on KeyAll
  message: "&aYou can edit this message in the KeyAll config.yml"

  # Message to be sent on ActionBar
  actionbar:
    enabled: true
    message: ""

  # Title to be sent
  title:
    enabled: true
    title: ""
    subtitle: "" # Subtitle
    fade-in: 2
    stay: 4
    fade-out: 2

# Latest sounds are supported
  sound:
    enabled: true
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1.0
    pitch: 1.0
